services:
  test-backend-1:
    build:
      context: .
      target: production
    image: test-backend-1
    container_name: test-backend-1
    depends_on:
      - test-backend-1-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: test-backend-1-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  test-backend-1-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: test-backend-1
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
